// Rose Ly — JAKIM prayer zones for Malaysia.
// Assigns to window.RL_ZONES so both the Setup Wizard and Mobile Admin
// can share the same zone list without duplication.
(function () {
  window.RL_ZONES = [
    { code: 'WLY01', label: 'Kuala Lumpur / Putrajaya' },
    { code: 'WLY02', label: 'Labuan' },
    { code: 'JHR01', label: 'Pulau Aur / Johor Timur' },
    { code: 'JHR02', label: 'Johor Bahru' },
    { code: 'JHR03', label: 'Kota Tinggi' },
    { code: 'JHR04', label: 'Mersing' },
    { code: 'JHR05', label: 'Kluang' },
    { code: 'JHR06', label: 'Pontian' },
    { code: 'JHR07', label: 'Segamat' },
    { code: 'JHR08', label: 'Muar' },
    { code: 'KDH01', label: 'Kota Setar / Alor Setar' },
    { code: 'KDH02', label: 'Kulim' },
    { code: 'KDH03', label: 'Kubang Pasu' },
    { code: 'KDH04', label: 'Baling' },
    { code: 'KDH05', label: 'Sik' },
    { code: 'KDH06', label: 'Pendang' },
    { code: 'KDH07', label: 'Yan' },
    { code: 'KDH08', label: 'Pokok Sena' },
    { code: 'KDH09', label: 'Langkawi' },
    { code: 'KLT01', label: 'Kota Bharu' },
    { code: 'KLT02', label: 'Pasir Mas' },
    { code: 'KLT03', label: 'Tanah Merah' },
    { code: 'KLT04', label: 'Pasir Puteh' },
    { code: 'KLT05', label: 'Bachok' },
    { code: 'KLT06', label: 'Tumpat' },
    { code: 'KLT07', label: 'Gua Musang' },
    { code: 'KLT08', label: 'Kuala Krai' },
    { code: 'MLK01', label: 'Melaka' },
    { code: 'NGS01', label: 'Seremban' },
    { code: 'NGS02', label: 'Jelebu' },
    { code: 'NGS03', label: 'Jempol' },
    { code: 'NGS04', label: 'Tampin' },
    { code: 'NGS05', label: 'Port Dickson / Kuala Pilah' },
    { code: 'NGS06', label: 'Rembau' },
    { code: 'PHG01', label: 'Pekan' },
    { code: 'PHG02', label: 'Rompin' },
    { code: 'PHG03', label: 'Maran' },
    { code: 'PHG04', label: 'Temerloh' },
    { code: 'PHG05', label: 'Bentong' },
    { code: 'PHG06', label: 'Kuantan' },
    { code: 'PHG07', label: 'Bera' },
    { code: 'PHG08', label: 'Raub' },
    { code: 'PHG09', label: 'Jerantut' },
    { code: 'PRK01', label: 'Tapah / Slim River' },
    { code: 'PRK02', label: 'Kuala Kangsar' },
    { code: 'PRK03', label: 'Pengkalan Hulu' },
    { code: 'PRK04', label: 'Hulu Perak' },
    { code: 'PRK05', label: 'Kerian' },
    { code: 'PRK06', label: 'Larut Matang' },
    { code: 'PRK07', label: 'Kinta (Ipoh)' },
    { code: 'PRK08', label: 'Perak Tengah' },
    { code: 'PRK09', label: 'Muallim' },
    { code: 'PLS01', label: 'Perlis' },
    { code: 'PNG01', label: 'Seberang Perai / Pulau Pinang' },
    { code: 'PNG02', label: 'Balik Pulau' },
    { code: 'SBH01', label: 'Kota Kinabalu' },
    { code: 'SBH02', label: 'Ranau' },
    { code: 'SBH03', label: 'Tawau' },
    { code: 'SBH04', label: 'Lahad Datu' },
    { code: 'SBH05', label: 'Sandakan' },
    { code: 'SBH06', label: 'Beaufort' },
    { code: 'SBH07', label: 'Keningau' },
    { code: 'SBH08', label: 'Sipitang' },
    { code: 'SBH09', label: 'Kudat' },
    { code: 'SBH10', label: 'Kinabatangan' },
    { code: 'SWK01', label: 'Miri' },
    { code: 'SWK02', label: 'Bintulu' },
    { code: 'SWK03', label: 'Sibu' },
    { code: 'SWK04', label: 'Sri Aman' },
    { code: 'SWK05', label: 'Kuching' },
    { code: 'SWK06', label: 'Kapit' },
    { code: 'SWK07', label: 'Bau / Lundu' },
    { code: 'SWK08', label: 'Samarahan' },
    { code: 'SWK09', label: 'Serian' },
    { code: 'SWK10', label: 'Betong' },
    { code: 'SGR01', label: 'Gombak / KL Timur' },
    { code: 'SGR02', label: 'Sabak Bernam' },
    { code: 'SGR03', label: 'Kuala Selangor' },
    { code: 'SGR04', label: 'Klang' },
    { code: 'SGR05', label: 'Petaling Jaya / Shah Alam' },
    { code: 'SGR06', label: 'Sepang' },
    { code: 'SGR07', label: 'Kuala Langat' },
    { code: 'SGR08', label: 'Hulu Selangor' },
    { code: 'SGR09', label: 'Hulu Langat' },
    { code: 'TRG01', label: 'Dungun' },
    { code: 'TRG02', label: 'Kemaman' },
    { code: 'TRG03', label: 'Kuala Terengganu' },
    { code: 'TRG04', label: 'Marang' },
    { code: 'TRG05', label: 'Hulu Terengganu' },
    { code: 'TRG06', label: 'Setiu' },
    { code: 'TRG07', label: 'Besut' },
  ];
})();
